### ISSUE TITLE
我参考您的项目实现了一个功能基本完善的自定义表单项目

### ISSUE THREAD

**Issue by Varsion** [wlmnzf/javascript-train#1]
您好，我参考您的这个项目实现了一个自定义表单系统，项目地址为[自定义表单](https://github.com/Varsion/Customize_form)
如果因擅自使用您的项目代码给您造成了不便，还请联系我。
谢谢

**Comment by wlmnzf** [comment]
> 您好，我参考您的这个项目实现了一个自定义表单系统，项目地址为[自定义表单](https://github.com/Varsion/Customize_form) 如果因擅自使用您的项目代码给您造成了不便，还请联系我。 谢谢

没关系，请尽情使用，加油！！
